### PR TITLE
Test PR - added (InGame) StartMatch event

### PR DESCRIPTION
**Pull request by hemisemidemipresent**
please correct me if I made an error in any way, if this works more events should be coming

### CODE REVIEW

**Comment by DisabledMallis** [comment]
I'll test it tomorrow, overall looks like a good PR

**Comment by DisabledMallis** [comment]
Ok so i know i said id check it like 2 days ago so uh... sorry about that... Ill check whenever I get the chance xd

**Comment by hemisemidemipresent** [comment]
if this is fine there will probably be like 10 more events tmr lol

**Comment by DisabledMallis** [comment]
By the way i dont think the game ever actually uses this method, the patch doesnt get called at all from what I can tell

**Comment by hemisemidemipresent** [comment]
weird, for me it works perfectly fine:
```cs
[HarmonyPatch(typeof(InGame), "StartMatch")]

    public class GameInit_Patch
    {
        [HarmonyPostfix]

        public static void Postfix()
        {
            Logger.Log("hey");
        }
    }
```

**Comment by hemisemidemipresent** [comment]
Also added `spawnBloon()` method for `InGame` [here](https://github.com/TDToolbox/NKHook6/pull/5/commits/45942042b848cbb62a910ce60b90cc37ece99f52)

(was supposed to be in a seperate PR but my finger slipped and I can be bothered to revert changes yet again)

**Comment by DisabledMallis** [comment]
You made the event cancellable, so I changed it to a prefix. Is it supposed to be a postfix? because postfix patches cannot dispatch cancellable events

**Comment by hemisemidemipresent** [comment]
Ah my bad, it wasn't supposed to cancellable, it should be postfix because if it is prefix `InGame` has issues

**Comment by DisabledMallis** [comment]
Alright I'll switch it back

**Comment by DisabledMallis** [comment]
I think im going to have to close this PR, theres so much wrong with it. Make a new PR, and please make sure the code actually compiles first! so many missing {, }, ;, typos, you name it, its there...

**Comment by hemisemidemipresent** [comment]
btw how do you compile NKH6 locally?

**Pull request closed without merging**
